### ISSUE TITLE
Seam problems

### ISSUE THREAD

**Issue by rrtt2323** [Fobri/Terraxel-Unity#1]
![image](https://github.com/Fobri/Terraxel-Unity/assets/12709491/fd189b80-5ef6-4e43-9088-9c537bdb9ae7)
Hotshot, I found that there are many gaps, what caused this?

**Comment by Fobri** [comment]
That happens because chunks with low LOD are simple 2D chunks. This works well for relatively flat terrains, but when there is a fast vertical shift in the terrain, like a cliff in this case, the seam between the 2D and 3D chunks breaks.
This can be fixed by turning off the 2D chunks completely at ChunkManager.cs method GenerateChunk (This option would be viable only for a small world size since generating 3D chunks is A LOT more expensive than the 2D chunks)
Another option would be to play around with how much overlap is allowed to happen between 2D and 3D chunks, at Jobs.cs:41
For example you could add an overlap allowance variable:
`var overlapAllowance = 2f * depthMultiplier;`
and adjust the check like this:
`if(height + overlapAllowance  >= chunkPos.y && height - overlapAllowance  <= chunkPos.y + chunkSize * depthMultiplier)`
Then you can keep making adjustments to the allowance to eliminate the gaps with your desired terrain shape.

**Comment by rrtt2323** [comment]
Completely turning off the 2d chunk made it impossible for me to start it. It's really expensive!
